- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
    ~/.config/nvim/init.vim: vim/vimrc
    ~/.dot: ''
    ~/.irssi:
    ~/.screenrc:
    ~/.shell:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule update --init --recursive
