- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
    ~/.dot: ''
    ~/.shell:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule update --init --recursive
