- defaults:
    link:
        create: true
        relink: true
        relative: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
    ~/.bash: bash
    ~/.config/mpv: mpv
    ~/.config/nvim/init.vim: vim/vimrc
    ~/.config/todo.cfg: todo.cfg
    ~/.gitconfig: git/gitconfig
    ~/.gitignore-global: git/gitignore-global
    ~/.irssi:
    ~/.npmrc:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - touch ~/.histfile
    - git submodule update --init --recursive
#    - vim +PluginInstall! +qall
