- defaults:
    link:
        create: true
        relink: true
        relative: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
    ~/.bash: bash
    ~/.config/git: git
    ~/.config/mpv: mpv
    ~/.config/nvim: nvim
    ~/.config/todo.cfg: todo.cfg
    ~/.config/tmux: tmux
    ~/.irssi:
    ~/.local/share/nvim/site/autoload: vim/autoload
    ~/.npmrc:
    ~/.screenrc:
    ~/.shell:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - touch ~/.histfile
    - git submodule update --init --recursive
    - mkdir -p ~/.local/share/nvim/site
#    - vim +PluginInstall! +qall
