- defaults:
    link:
        create: true
        relink: true
        relative: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
    ~/.bash: bash
    ~/.config/git: git
    ~/.config/mpv: mpv
    ~/.config/npm: npm
    ~/.config/nvim: nvim
    ~/.config/todo: todo
    ~/.pam_environment: pam/environment
    ~/.shell:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - touch ~/.histfile
    - git submodule update --init --recursive
    - mkdir -p ~/.local/share/nvim/site
