- defaults:
    link:
        create: true
        relink: true

- clean: ['~', '~/.config']

- link:
    ~/.bashrc:
    ~/.config/nvim/init.vim: vim/vimrc
    ~/.dotfiles: ''
    ~/.gitconfig: git/gitconfig
    ~/.gitignore-global: git/gitignore-global
    ~/.irssi:
    ~/.screenrc:
    ~/.shell:
    ~/.tmux.conf:
    ~/.vim:
    ~/.zsh:
    ~/.zshrc:

- shell:
    - git submodule update --init --recursive
